[workspace]
members = [
    "packages/token_migration",
]


[workspace.package]
version = "0.1.0"
edition = "2024_07"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.12.2"
snforge_std = "0.49.0"
assert_macros = "2.12.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", rev = "0e51722f231c0913915945d3df89e43cbb5cfc38" }
starkware_utils = { git = "https://github.com/starkware-libs/starkware-starknet-utils", branch = "oz-3.0.0-alpha.2" }
starkware_utils_testing = { git = "https://github.com/starkware-libs/starkware-starknet-utils", branch = "oz-3.0.0-alpha.2" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]
casm = true

[[test]]
name = "unittest"


[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
