[workspace]
members = [
    "packages/token_migration",
]


[workspace.package]
version = "0.1.0"
edition = "2024_07"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.12.2"
snforge_std = "0.49.0"
assert_macros = "2.12.2"
openzeppelin = "2.0.0"
openzeppelin_testing = "4.2.0"
starkware_utils = { git ="https://github.com/starkware-libs/starkware-starknet-utils", rev="38b172ca577db94ea5cb3d227b2cfd9716c75386" }
starkware_utils_testing = { git="https://github.com/starkware-libs/starkware-starknet-utils", rev="38b172ca577db94ea5cb3d227b2cfd9716c75386" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[[target.starknet-contract]]
casm = true

[[test]]
name = "unittest"


[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
